[package]
name = "monar"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

[dev-dependencies]
insta = "1.34.0"
criterion = "0.5"
assert_cmd = "2.0"

[[bench]]
name = "greeting_benchmark"
harness = false
